# Generated by Django 4.2.4 on 2023-08-19 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('limite', models.FloatField()),
                ('id_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.presupuestos')),
            ],
        ),
    ]
