# Generated by Django 4.2.4 on 2023-08-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_categoria_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='movimientos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
